#Making a stair using rectangles in turtle.
import turtle
turtle.bgcolor("black")
turtle.pencolor('red')
turtle.pensize(5)
turtle.forward(50)
turtle.setheading(90)
turtle.forward(100)
turtle.setheading(180)
turtle.forward(50)
turtle.setheading(270)
turtle.forward(100)
import turtle
turtle.pencolor('blue')
turtle.pensize(5)
turtle.forward(50)
turtle.setheading(90)
turtle.forward(100)
turtle.setheading(180)
turtle.forward(50)
turtle.setheading(270)
turtle.forward(100)
import turtle
turtle.pencolor('yellow')
turtle.pensize(5)
turtle.forward(50)
turtle.setheading(90)
turtle.forward(100)
turtle.setheading(180)
turtle.forward(50)
turtle.setheading(270)
turtle.forward(100)
import turtle
turtle.pencolor('pink')
turtle.pensize(5)
turtle.forward(50)
turtle.setheading(90)
turtle.forward(100)
turtle.setheading(180)
turtle.forward(50)
turtle.setheading(270)
turtle.forward(100)
import turtle
turtle.pencolor('orange')
turtle.pensize(5)
turtle.forward(50)
turtle.setheading(90)
turtle.forward(100)
turtle.setheading(180)
turtle.forward(50)
turtle.setheading(270)
turtle.forward(100)
import turtle
turtle.pencolor('white')
turtle.pensize(5)
turtle.forward(50)
turtle.setheading(90)
turtle.forward(100)
turtle.setheading(180)
turtle.forward(50)
turtle.setheading(270)
turtle.forward(100)
import turtle
turtle.pencolor('grey')
turtle.pensize(5)
turtle.forward(50)
turtle.setheading(90)
turtle.forward(100)
turtle.setheading(180)
turtle.forward(50)
turtle.setheading(270)
turtle.forward(100)
